# WARNING - Generated by {fusen} from /dev/auc.Rmd: do not edit by hand

test_that("opt_sp works", {
  res <- opt_sp(k = 0.13, pve = 0.26, se = 0.99)
  expect_true(inherits(opt_sp, "function")) 
  expect_type(res, "double")
})
