# WARNING - Generated by {fusen} from /dev/auc.Rmd: do not edit by hand

test_that("opt_se works", {
  res <- opt_se(k = 0.13, pve = 0.26, sp = 0.99)
  expect_true(inherits(opt_se, "function")) 
  expect_type(res, "double")
})
