# WARNING - Generated by {fusen} from /dev/auc.Rmd: do not edit by hand

#' Estimate the Maximum AUC
#' 
#' Estimate the maximum AUC of a polygenic risk score based on the population prevalence of a disease `k` and the proportion of variability explained by the PRS `pve`.
#' 
#' @param k (numeric; range 0-1) Population prevalence of the disease of interest
#' @param pve (numeric; range 0-1) Proportion of variability explained by the PRS
#' @param n.bins (integer) Number of bins for estimating the AUC (default = 100)
#'
#' @return A numeric value for the maximum AUC
#' @export
#' @examples
#' max_auc(k = 0.13, pve = 0.26)
max_auc <- function(k, pve, n.bins=100){
    checkmate::assert_numeric(k, lower = 0, upper = 1)
    checkmate::assert_numeric(pve, lower = 0, upper = 1)
    checkmate::assert_numeric(n.bins)
  
    Q <- makeQ(n.bins=n.bins)
    #check concavity to ensure that Q is negative semidefinite
    eigen.vals <- eigen(x=Q, symmetric=TRUE, only.values=TRUE)$values
    if (!all(eigen.vals<=0)){ warning('The matrix Q is not concave') }
    #constraints: prevalence, pve, 0<=p, p<=1, sum(p)<=1
    Amat <- rbind((1:n.bins)/n.bins, (1:n.bins)^2/(n.bins^2), diag(n.bins), -diag(n.bins), rep(-1, n.bins))
    rhs <- c(k, k*(1-k)*pve+k^2, numeric(n.bins), rep(-1, n.bins), -1)
    #run quadratic program over p
    qp.res <- quadprog::solve.QP(Dmat=-Q, dvec=numeric(n.bins), Amat=t(Amat), bvec=rhs, meq=2)
    auc <- (-2*qp.res$value+n.bins^2*k)/(n.bins^2*k*(1-k))
    return(auc)
}

#' makeQ
#'
#' @param n.bins (integer) Number of bins
#'
#' @return a matrix

makeQ <- function(n.bins){
    mat <- matrix(0,nrow=n.bins,ncol=n.bins)
    for (i in 1:nrow(mat)){
        for (j in 1:ncol(mat)){
            if (i>j){ mat[i,j] <- -(n.bins+i)*j/2 } else { mat[i,j] <- -(n.bins+j)*i/2 }
        }
    }
    return(mat)
}
