# WARNING - Generated by {fusen} from /dev/auc.Rmd: do not edit by hand

#' Optimal Sensitivity
#'
#' These functions estimate the optimal (maximal or minimal) sensitivity of a PRS.
#' 
#' @param thresh.vector (numeric) Vector of thresholds
#' @param k (numeric; range 0-1) Population prevalence of the disease of interest
#' @param pve (numeric; range 0-1) Proportion of variability explained by the PRS
#' @param sp (numeric; range 0-1) Specificity
#' @param n.bins (integer) Number of bins for estimating the AUC (default = 100)
#' @param direction (character) `"max"` or `"min"`
#'
#' @return A numeric valuve for the optimal sensitivity
#' 
#' @export

#' @examples
#' opt_se(k = 0.13, pve = 0.26, sp = 0.99)
opt_se <- function(k, pve, sp, n.bins=1000, thresh.vector=seq(from=1,to=n.bins,by=10), direction="max"){
    #vector of sensitivity at each threshold
    se.tmp.v <- apply(X=as.matrix(thresh.vector), MARGIN=1, FUN=optSeGivenThresh, k=k, pve=pve, n.bins=n.bins,
    sp=sp, direction=direction)
    se <- max(se.tmp.v)
    return(se)
}


#' @noRd
optSeGivenThresh <- function(thresh, k, pve, sp, n.bins, direction="max"){

    obj <- c(rep(0, thresh), thresh:n.bins)/(n.bins*k)
    sp.coeff <- c(n.bins-0:(thresh-1), rep(0, n.bins-thresh+1))/(n.bins*(1-k))
    #constraints: avg risk=k, pve, sp, sum(p)=1, 0<=p, p<=1
    Amat <- rbind((0:n.bins)/n.bins, (0:n.bins)^2/(n.bins^2), sp.coeff, rep(1,n.bins+1), diag(n.bins+1), -diag(n.bins+1))
    rhs <- c(k, k*(1-k)*pve+k^2, sp, 1, numeric(n.bins+1), rep(-1,n.bins+1))
    lp.res <- lpSolve::lp(direction=direction, objective.in=obj, const.mat=Amat, const.dir=c(rep("=",4), 
    rep(">=", 2*n.bins+2)), const.rhs=rhs)
    return(lp.res$objval)
}

